import { SideNavInterface } from '@app/@layout/vertical/side-nav.type';
import { PermissionKey as PK } from '@app/@shared/@types/permission';
import { extract } from '@app/i18n';

export const MENU: SideNavInterface[] = [
  {
    path: 'case-management',
    title: extract('Case Management'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'home',
    permissions: [PK.VIEW_PATIENTS],
    submenu: [
      {
        path: 'case-management/patients',
        title: extract('Patient list'),
        iconType: '',
        iconTheme: '',
        permissions: [PK.VIEW_PATIENTS, PK.MANAGE_PATIENTS],
        submenu: [],
      },
      {
        path: 'case-management/case-managers',
        title: extract('Case Managers'),
        permissions: [PK.VIEW_PATIENTS, PK.MANAGE_PATIENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'case-management/informants',
        title: extract('Informants'),
        permissions: [PK.VIEW_PATIENTS, PK.MANAGE_PATIENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'assessments',
    title: extract('Assessments'),
    permissions: [PK.VIEW_ASSESSMENTS],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'edit',
    submenu: [
      {
        path: 'assessments/plan-assessments',
        title: extract('Plan assessment'),
        permissions: [PK.MANAGE_ASSESSMENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'assessments',
        title: extract('Planned Assessments'),
        permissions: [PK.VIEW_ASSESSMENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'reports',
    title: extract('Reports'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'file-text',
    submenu: [
      {
        path: 'reports',
        title: extract('All Reports'),
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'user-management',
    title: extract('User Management'),
    permissions: [PK.VIEW_USERS, PK.MANAGE_USERS],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'user',
    submenu: [
      {
        path: 'user-management/users',
        title: extract('List users'),
        permissions: [PK.MANAGE_USERS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'user-management/user-form',
        title: extract('New user'),
        permissions: [PK.MANAGE_USERS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'administration',
    title: extract('Administration'),
    permissions: [PK.MANAGE_ROLES, PK.MANAGE_SETTINGS, PK.MANAGE_DEPARTMENTS],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'setting',
    submenu: [
      {
        path: 'administration/permission-matrix',
        title: extract('Permission Matrix'),
        permissions: [PK.VIEW_ROLES],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/permissions',
        title: extract('Permissions'),
        permissions: [PK.VIEW_ROLES],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/roles',
        title: extract('Roles'),
        permissions: [PK.MANAGE_ROLES],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/departments',
        title: extract('Departments'),
        permissions: [PK.MANAGE_DEPARTMENTS],
        iconType: '',
        iconTheme: '',
        icon: '',
        submenu: [],
      },
      {
        path: 'administration/settings',
        title: extract('Settings'),
        permissions: [PK.MANAGE_SETTINGS],
        iconType: '',
        iconTheme: '',
        submenu: [
          {
            path: 'administration/settings/system-configuration',
            title: extract('System Configuration'),
            permissions: [PK.MANAGE_SETTINGS],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
          {
            path: 'administration/settings/patient-statuses',
            title: extract('Patient Statuses'),
            permissions: [PK.MANAGE_SETTINGS],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    path: 'feedback',
    title: extract('Feedback'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'message',
    submenu: [],
  },
];
