import { SideNavInterface } from '@app/@layout/backend/side-nav.type';
import { PermissionKey as PK } from '@app/@shared/@types/permission';
import { extract } from '@app/i18n';

export const MENU: SideNavInterface[] = [
  {
    path: 'dashboard',
    title: extract('Dashboard'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'home',
    submenu: [],
  },
  {
    path: 'case-management',
    title: extract('Case Management'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'audit',
    permissions: [PK.VIEW_PATIENTS, PK.MANAGE_PATIENTS],
    submenu: [
      {
        path: 'case-management/patients',
        title: extract('Patient list'),
        iconType: '',
        iconTheme: '',
        permissions: [PK.VIEW_PATIENTS],
        submenu: [],
      },
      {
        path: 'case-management/profile',
        title: extract('Create Patient'),
        iconType: '',
        iconTheme: '',
        permissions: [PK.MANAGE_PATIENTS],
        submenu: [],
      },
    ],
  },
  {
    path: 'questionnaire-management',
    title: extract('Questionnaires'),
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'file',
    permissions: [PK.VIEW_QUESTIONNAIRES, PK.MANAGE_QUESTIONNAIRES],
    submenu: [
      {
        path: 'questionnaire-management/questionnaire-list',
        title: extract('Questionnaires list'),
        permissions: [PK.VIEW_QUESTIONNAIRES],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'questionnaire-management/questionnaire-form',
        title: extract('Upload questionnaire'),
        permissions: [PK.MANAGE_QUESTIONNAIRES],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'assessments',
    title: extract('Assessments'),
    permissions: [PK.VIEW_ASSESSMENTS, PK.MANAGE_ASSESSMENTS],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'edit',
    submenu: [
      {
        path: 'assessments/plan-assessments',
        title: extract('Plan assessment'),
        permissions: [PK.MANAGE_ASSESSMENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'assessments',
        title: extract('Planned Assessments'),
        permissions: [PK.VIEW_ASSESSMENTS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'user-management',
    title: extract('User Management'),
    permissions: [PK.VIEW_USERS, PK.MANAGE_USERS],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'user',
    submenu: [
      {
        path: 'user-management/users',
        title: extract('List users'),
        permissions: [PK.VIEW_USERS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'user-management/user-form',
        title: extract('New user'),
        permissions: [PK.MANAGE_USERS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
    ],
  },
  {
    path: 'administration',
    title: extract('Administration'),
    permissions: [PK.VIEW_ROLES_PERMISSIONS, PK.VIEW_SETTINGS, PK.VIEW_SYSCONF],
    iconType: 'nzIcon',
    iconTheme: 'outline',
    icon: 'setting',
    submenu: [
      {
        path: 'administration/permission-matrix',
        title: extract('Permission Matrix'),
        permissions: [PK.VIEW_ROLES_PERMISSIONS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/permissions',
        title: extract('Permissions'),
        permissions: [PK.VIEW_ROLES_PERMISSIONS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/roles',
        title: extract('Roles'),
        permissions: [PK.VIEW_ROLES_PERMISSIONS],
        iconType: '',
        iconTheme: '',
        submenu: [],
      },
      {
        path: 'administration/departments',
        title: extract('Departments'),
        permissions: [PK.VIEW_SETTINGS],
        iconType: '',
        iconTheme: '',
        icon: '',
        submenu: [],
      },
      {
        path: 'administration/settings',
        title: extract('Settings'),
        permissions: [PK.VIEW_SETTINGS, PK.VIEW_SYSCONF],
        iconType: '',
        iconTheme: '',
        submenu: [
          {
            path: 'administration/settings/system-configuration',
            title: extract('System Configuration'),
            permissions: [PK.VIEW_SYSCONF],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
          {
            path: 'administration/settings/patient-statuses',
            title: extract('Patient Statuses'),
            permissions: [PK.VIEW_SETTINGS],
            iconType: '',
            iconTheme: '',
            submenu: [],
          },
        ],
      },
    ],
  },
];
