import { FieldGroup } from '@shared/components/field-generator/field.group';

const searchForm: FieldGroup[] = [
  {
    fields: [
      {
        value: '',
        title: 'search',
        label: 'Search',
        description: 'Enter search field',
        type: 'text',
        validationMessage: 'please enter value',
        isRequired: true,
        span: 24,
      },
      {
        value: '',
        title: 'select',
        label: 'Search Patient',
        description: 'Search and select patient',
        type: 'select',
        validationMessage: 'please enter value',
        isRequired: true,
        options: [
          { label: 'Option 1', value: 1 },
          { label: 'Option 2', value: 2 },
          { label: 'Option 3', value: 3 },
          { label: 'Option 4', value: 4 },
        ],
        span: 24,
      },
      {
        value: '',
        title: 'remote search',
        label: 'Search',
        description: 'Search',
        type: 'search',
        iconName: 'search',
        validationMessage: 'please enter value',
        isRequired: true,
        options: [],
        span: 24,
      },
      {
        value: '',
        title: 'Date',
        label: 'Search by date',
        description: 'Enter date',
        type: 'date',
        validationMessage: 'please enter date',
        isRequired: true,
        span: 24,
      },
      {
        value: [],
        title: 'Check Box',
        label: 'Select',
        description: 'Select multiple',
        type: 'checkBox',
        validationMessage: 'please select',
        isRequired: true,
        options: [
          { label: 'Option 1', value: 1 },
          { label: 'Option 2', value: 2 },
          { label: 'Option 3', value: 3 },
          { label: 'Option 4', value: 4 },
        ],
        span: 24,
      },
      {
        value: '',
        title: 'Radio',
        label: 'Select',
        description: 'Select one',
        type: 'radio',
        validationMessage: 'please select one',
        isRequired: true,
        options: [
          { label: 'Option 1', value: 1 },
          { label: 'Option 2', value: 2 },
          { label: 'Option 3', value: 3 },
          { label: 'Option 4', value: 4 },
        ],
        span: 24,
      },
      {
        value: '',
        title: 'Text Area',
        label: 'Text area',
        description: 'this is the text area',
        type: 'textArea',
        validationMessage: 'please type',
        isRequired: true,
        span: 24,
      },
      {
        value: '',
        title: 'Plan',
        type: 'submitButton',
        span: 24,
      },
    ],
  },
];

export const patientForms = {
  searchForm,
};
