import { Form } from '@shared/components/form/@types/form';

export const planAssessmentForm: Form = {
  submitButtonText: 'Plan',
  editButtonText: 'Edit Assessment',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Assessment Name',
          label: 'Assessment Name',
          description: 'enter assessment name',
          type: 'text',
          validationMessage: 'please enter assessment name',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'patientId',
          title: 'Select a patient',
          label: 'Select a patient',
          description: 'Search and Select a patient',
          type: 'search',
          validationMessage: 'please select patient',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'clinicianId',
          title: 'Select a clinician',
          label: 'Select a clinician',
          description: 'Search and Select a clinician',
          type: 'search',
          validationMessage: 'please select clinician',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'informantId',
          title: 'Select a informant',
          label: 'Select a informant',
          description: 'Search and Select an informant',
          type: 'search',
          validationMessage: 'please select informant',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          title: 'Assessment Date',
          name: 'date',
          label: 'Assessment Date',
          description: 'select assessment date',
          type: 'date',
          validationMessage: 'please enter date of birth',
          isRequired: false,
          span: 24,
        },
      ],
    },
  ],
};
