import { Form } from '@shared/components/form/@types/form';

export const ConsentForm: Form = {
  submitButtonText: 'tables.consents.saveConsent',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Consent Name',
          label: 'Consent Name',
          translationPath: 'tables.consents.name',
          description: 'tables.consents.name',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'title',
          title: 'Modal Title',
          label: 'Modal Title',
          translationPath: 'tables.consents.title',
          description: 'tables.consents.title',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'description',
          title: 'Consent Description',
          label: 'Consent Description',
          translationPath: 'tables.consents.description',
          description: 'tables.consents.description',
          validationMessage: 'tables.consents.validationMessage',
          type: 'wysiwyg',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent1',
          title: 'Consent 1',
          label: 'Consent 1',
          translationPath: 'tables.consents.consent1',
          description: 'tables.consents.consent1',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent2',
          title: 'Consent 2',
          label: 'Consent 2',
          translationPath: 'tables.consents.consent2',
          description: 'tables.consents.consent2',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent3',
          title: 'Consent 3',
          label: 'Consent 3',
          translationPath: 'tables.consents.consent3',
          description: 'tables.consents.consent3',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent4',
          title: 'Consent 4',
          label: 'Consent 4',
          translationPath: 'tables.consents.consent4',
          description: 'tables.consents.consent4',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent5',
          title: 'Consent 5',
          label: 'Consent 5',
          translationPath: 'tables.consents.consent5',
          description: 'tables.consents.consent5',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent6',
          title: 'Consent 6',
          label: 'Consent 6',
          translationPath: 'tables.consents.consent6',
          description: 'tables.consents.consent6',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent7',
          title: 'Consent 7',
          label: 'Consent 7',
          translationPath: 'tables.consents.consent7',
          description: 'tables.consents.consent7',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'acceptLabel',
          title: 'Accept button label',
          label: 'Accept button label',
          translationPath: 'tables.consents.acceptLabel',
          description: 'tables.consents.acceptLabel',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'submitLabel',
          title: 'Submit button label',
          label: 'Submit button label',
          translationPath: 'tables.consents.submitLabel',
          description: 'tables.consents.submitLabel',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'submitContent',
          title: 'Submit Content',
          label: 'Submit Content',
          translationPath: 'tables.consents.submitContent',
          description: 'tables.consents.submitContent',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
