import { Form } from '@shared/components/form/@types/form';

export const ConsentForm: Form = {
  submitButtonText: 'tables.consents.saveConsent',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Consent Name',
          label: 'Consent Name',
          translationPath: 'tables.consents.name',
          description: 'tables.consents.name',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'description',
          title: 'Consent Description',
          label: 'Consent Description',
          translationPath: 'tables.consents.description',
          description: 'tables.consents.description',
          validationMessage: 'tables.consents.validationMessage',
          type: 'text',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent1',
          title: 'Consent 1',
          label: 'Consent 1',
          translationPath: 'tables.consents.consent1',
          description: 'tables.consents.consent1',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'consent2',
          title: 'Consent 2',
          label: 'Consent 2',
          translationPath: 'tables.consents.consent2',
          description: 'tables.consents.consent2',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'submitContent',
          title: 'Submit Content',
          label: 'Submit Content',
          translationPath: 'tables.consents.submitContent',
          description: 'tables.consents.submitContent',
          type: 'text',
          validationMessage: 'tables.consents.validationMessage',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
