import { Form } from '../../../@shared/components/form/@types/form';

export const ReportForm: Form = {
  submitButtonText: 'forms.createReportForm.saveReport',
  editButtonText: 'Edit Report',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'name',
          title: 'Report Name',
          label: 'Report Name',
          translationPath: 'forms.createReportForm.reportName',
          description: 'forms.createReportForm.descriptionReportName',
          type: 'text',
          validationMessage: 'forms.createReportForm.validationReportName',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'resources',
          title: 'Report resources',
          label: 'Report resources',
          translationPath: 'forms.createReportForm.resources',
          description: 'forms.createReportForm.descriptionResources',
          type: 'select',
          options: [
            { label: 'forms.createReportForm.patients', value: 'Patients' },
            { label: 'forms.createReportForm.dashboard', value: 'Dashboard' },
          ],
          validationMessage: 'forms.createReportForm.validationResources',
          isRequired: true,
          disabled: false,
          span: 24,
        },
        {
          value: '',
          name: 'description',
          title: 'Report description',
          label: 'Report description',
          translationPath: 'forms.createReportForm.description',
          description: 'Enter Report description',
          type: 'textArea',
          validationMessage: 'Please enter report description',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'url',
          title: 'Report url',
          label: 'Report url',
          translationPath: 'forms.createReportForm.url',
          description: 'forms.createReportForm.descriptionUrl',
          type: 'text',
          validationMessage: 'forms.createReportForm.validationUrl',
          isRequired: true,
          disabled: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'repositoryLink',
          title: 'Report repository link',
          label: 'Report repository link',
          translationPath: 'forms.createReportForm.repositoryLink',
          description: 'forms.createReportForm.descriptionRespository',
          type: 'text',
          validationMessage: 'forms.createReportForm.validationRespository',
          isRequired: false,
          disabled: false,
          span: 24,
          options: [],
        },
        {
          value: false,
          name: 'status',
          title: 'Report repository status',
          label: 'Report repository status',
          translationPath: 'forms.createReportForm.reportStatus',
          description: 'Enter Report repository status',
          type: 'radio',
          options: [
            { label: 'On', value: true },
            { label: 'Off', value: false },
          ],
          validationMessage: 'Please enter Report repository status',
          isRequired: false,
          disabled: false,
          span: 24,
        },
        // {
        //   value: false,
        //   name: 'anonymus',
        //   title: 'Report repository anonymus',
        //   label: 'Report repository anonymus',
        //   translationPath: 'forms.createReportForm.anonymus',
        //   description: 'Enter Report repository anonymus',
        //   type: 'radio',
        //   options: [
        //     { label: 'Yes', value: true },
        //     { label: 'No', value: false },
        //   ],
        //   validationMessage: 'please Enter Report repository anonymus',
        //   isRequired: false,
        //   disabled: false,
        //   span: 24,
        // },
      ],
    },
  ],
};
