import { Form } from '@shared/components/form/@types/form';
import { getNames } from 'i18n-iso-countries';

export const CaregiversPatientForm: Form = {
  submitButtonText: 'Save',
  editButtonText: 'Edit',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'relation',
          title: 'Relation To Patient',
          label: 'Relation',
          translationPath: 'forms.patients.relation',
          description: 'Enter contact relation',
          type: 'select',
          options: [
            { label: 'Mother', value: 'Mother' },
            { label: 'Father', value: 'Father' },
            { label: 'Grandparent', value: 'Grandparent' },
            { label: 'Uncle/Aunt', value: 'Uncle/Aunt' },
            { label: 'Extended Family', value: 'Extended Family' },
            { label: 'Legal Guardian', value: 'Legal Guardian' },
            { label: 'Family Doctor', value: 'Family Doctor' },
            { label: 'External Paediatrician', value: 'External Paediatrician' },
            { label: 'External Psychotherapist', value: 'External Psychotherapist' },
            { label: 'External Psychologist', value: 'External Psychologist' },
            { label: 'External Social Worker', value: 'External Social Worker' },
            { label: 'External Nurse', value: 'External Nurse' },
            { label: 'Emergency Department', value: 'Emergency Department' },
            { label: 'Friend', value: 'Friend' },
            { label: 'Neighbour', value: 'Neighbour' },
            { label: 'Teacher', value: 'Teacher' },
            { label: 'School Representative', value: 'School Representative' },
            { label: 'Advisor', value: 'Advisor' },
            { label: 'Legal Advisor', value: 'Legal Advisor' },
            { label: 'Assistance', value: 'Assistance' },
            { label: 'Supervisor', value: 'Supervisor' },
            { label: 'Other', value: 'Other' },
          ],
          validationMessage: 'please enter contact relation',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'emergency',
          title: 'Emergency Contact',
          label: 'Emergency',
          translationPath: 'forms.patients.emergency',
          type: 'radio',
          options: [
            { label: 'Yes', value: true },
            { label: 'No', value: false },
          ],
          validationMessage: 'please enter contact emergency',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'note',
          title: 'Note',
          label: 'Note',
          translationPath: 'forms.patients.note',
          description: 'Enter contact note',
          type: 'textArea',
          validationMessage: 'please enter contact emergency',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'phone',
          title: 'Phone',
          label: 'Phone',
          // disabled: true,
          translationPath: 'forms.patients.phone',
          description: 'Enter contact phone',
          type: 'text',
          validationMessage: 'please enter contact phone',
          isRequired: true,
          span: 13,
        },
        {
          value: '',
          name: 'firstName',
          title: 'First Name',
          label: 'First Name',
          // disabled: true,
          translationPath: 'forms.patients.firstName',
          description: 'Enter contact first name',
          type: 'text',
          validationMessage: 'please enter contact first name',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'middleName',
          title: 'Middle Name',
          label: 'Middle Name',
          // disabled: true,
          translationPath: 'forms.patients.middleName',
          description: 'Enter contact middle name',
          type: 'text',
          validationMessage: 'please enter contact middle name',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'lastName',
          title: 'Last Name',
          label: 'Last Name',
          // disabled: true,
          translationPath: 'forms.patients.lastName',
          description: 'Enter contact last name',
          type: 'text',
          validationMessage: 'please enter contact last name',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'email',
          title: 'Email',
          label: 'Email',
          // disabled: true,
          translationPath: 'forms.patients.email',
          description: 'Enter contact email',
          type: 'text',
          validationMessage: 'please enter contact email',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'street',
          title: 'Street',
          label: 'Street',
          // disabled: true,
          translationPath: 'forms.patients.street',
          description: 'Enter contact email',
          type: 'text',
          validationMessage: 'please enter contact street',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'number',
          title: 'Number',
          label: 'Number',
          // disabled: true,
          translationPath: 'forms.patients.number',
          description: 'Enter contact number',
          type: 'text',
          validationMessage: 'please enter contact number',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'apartment',
          title: 'Apartment',
          label: 'Apartment',
          // disabled: true,
          translationPath: 'forms.patients.apartment',
          description: 'Enter contact apartment',
          type: 'text',
          validationMessage: 'please enter contact apartment',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'place',
          title: 'Place',
          label: 'Place',
          // disabled: true,
          translationPath: 'forms.patients.place',
          description: 'Enter contact place',
          type: 'text',
          validationMessage: 'please enter contact place',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'postalCode',
          title: 'Postal Code',
          label: 'Postal Code',
          // disabled: true,
          translationPath: 'forms.patients.postalCode',
          description: 'Enter contact Postal Code',
          type: 'text',
          validationMessage: 'please enter contact Postal Code',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'country',
          title: 'Country',
          label: 'Country',
          // disabled: true,
          translationPath: 'forms.patients.country',
          description: 'Enter contact country',
          type: 'select',
          validationMessage: 'please enter contact country',
          isRequired: false,
          span: 12,
          options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
        },
      ],
    },
  ],
};
