import { Form } from '@shared/components/form/@types/form';
import { Field } from '@shared/components/form/@types/field';

export const EmergencyContactForm: Form = {
  submitButtonText: 'Submit Contact',
  editButtonText: 'Submit Contact',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'emergencyContacts',
          title: 'Emergency Contact',
          label: 'Emergency Contact',
          translationPath: 'forms.patients.emergencyContacts',
          description: 'Enter emergency contact',
          type: 'array',
          validationMessage: 'please alternative enter phone number',
          isRequired: false,
          span: 24,
          rows: [],
          children: [
            {
              value: '',
              name: 'firstName',
              title: 'First Name',
              label: 'First Name',
              translationPath: 'forms.patients.firstName',
              description: 'Enter contact first name',
              type: 'text',
              validationMessage: 'please enter contact first name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'middleName',
              title: 'Middle Name',
              label: 'Middle Name',
              translationPath: 'forms.patients.middleName',
              description: 'Enter contact middle name',
              type: 'text',
              validationMessage: 'please enter contact middle name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'lastName',
              title: 'Last Name',
              label: 'Last Name',
              translationPath: 'forms.patients.lastName',
              description: 'Enter contact last name',
              type: 'text',
              validationMessage: 'please enter contact last name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'email',
              title: 'Email',
              label: 'Email',
              translationPath: 'forms.patients.email',
              description: 'Enter contact email',
              type: 'text',
              validationMessage: 'please enter contact email',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'phone',
              title: 'Phone',
              label: 'Phone',
              translationPath: 'forms.patients.phone',
              description: 'Enter contact phone',
              type: 'text',
              validationMessage: 'please enter contact phone',
              isRequired: false,
              span: 12,
            },
          ],
        },
      ],
    },
  ],
};
