import { Form } from '@shared/components/form/@types/form';

export const EmergencyContactForm: Form = {
  submitButtonText: 'Submit Contact',
  editButtonText: 'Submit Contact',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'emergencyContacts',
          title: 'Emergency Contact',
          label: 'Emergency Contact',
          translationPath: 'forms.patients.emergencyContacts',
          description: 'Enter emergency contact',
          type: 'array',
          validationMessage: 'please alternative enter phone number',
          isRequired: false,
          span: 24,
          rows: [],
          children: [
            {
              value: '',
              name: 'firstName',
              title: 'First Name',
              label: 'First Name',
              translationPath: 'forms.patients.firstName',
              description: 'Enter contact first name',
              type: 'text',
              validationMessage: 'please enter contact first name',
              isRequired: true,
              span: 8,
            },
            {
              value: '',
              name: 'middleName',
              title: 'Middle Name',
              label: 'Middle Name',
              translationPath: 'forms.patients.middleName',
              description: 'Enter contact middle name',
              type: 'text',
              validationMessage: 'please enter contact middle name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'lastName',
              title: 'Last Name',
              label: 'Last Name',
              translationPath: 'forms.patients.lastName',
              description: 'Enter contact last name',
              type: 'text',
              validationMessage: 'please enter contact last name',
              isRequired: true,
              span: 8,
            },
            {
              value: '',
              name: 'email',
              title: 'Email',
              label: 'Email',
              translationPath: 'forms.patients.email',
              description: 'Enter contact email',
              type: 'text',
              validationMessage: 'please enter contact email',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'phone',
              title: 'Phone',
              label: 'Phone',
              translationPath: 'forms.patients.phone',
              description: 'Enter contact phone',
              type: 'text',
              validationMessage: 'please enter contact phone',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'relation',
              title: 'Relation To Patient',
              label: 'Relation',
              translationPath: 'forms.patients.relation',
              description: 'Enter contact relation',
              type: 'select',
              options: [
                { label: 'Mother', value: 'string' },
                { label: 'Father', value: 'string' },
                { label: 'Grandparent', value: 'string' },
                { label: 'Uncle/Aunt', value: 'string' },
                { label: 'Extended Family', value: 'string' },
                { label: 'Legal Guardian', value: 'string' },
                { label: 'Family Doctor', value: 'string' },
                { label: 'External Paediatrician', value: 'string' },
                { label: 'External Psychotherapist', value: 'string' },
                { label: 'External Psychologist', value: 'string' },
                { label: 'External Social Worker', value: 'string' },
                { label: 'External Nurse', value: 'string' },
                { label: 'Emergency Department', value: 'string' },
                { label: 'Friend', value: 'string' },
                { label: 'Neighbour', value: 'string' },
                { label: 'Teacher', value: 'string' },
                { label: 'School Representative', value: 'string' },
                { label: 'Advisor', value: 'string' },
                { label: 'Legal Advisor', value: 'string' },
                { label: 'Assistance', value: 'string' },
                { label: 'Supervisor', value: 'string' },
                { label: 'Other', value: 'string' },
              ],
              validationMessage: 'please enter contact relation',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'emergency',
              title: 'Emergency Contact',
              label: 'Emergency',
              translationPath: 'forms.patients.emergency',
              type: 'checkBox',
              options: [
                { label: 'Yes', value: 'Yes' },
                { label: 'No', value: 'No' },
              ],
              validationMessage: 'please enter contact emergency',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'note',
              title: 'Note',
              label: 'Note',
              translationPath: 'forms.patients.note',
              description: 'Enter contact note',
              type: 'text',
              validationMessage: 'please enter contact emergency',
              isRequired: false,
              span: 12,
            },
          ],
        },
      ],
    },
  ],
};
