import { Form } from '@shared/components/form/@types/form';

export const InformantForm: Form = {
  submitButtonText: 'Submit Informant',
  editButtonText: 'Submit Informant',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'firstName',
          title: 'First Name',
          label: 'First Name',
          description: 'enter first name',
          type: 'text',
          validationMessage: 'please enter first name',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'middleName',
          title: 'Middle Name',
          label: 'Middle Name',
          description: 'enter middle name',
          type: 'text',
          validationMessage: 'please enter middle name',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'lastName',
          title: 'Last Name',
          label: 'Last Name',
          description: 'enter last name',
          type: 'text',
          validationMessage: 'please enter last name',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'phone',
          title: 'Phone',
          label: 'Phone',
          description: 'enter phone',
          type: 'text',
          validationMessage: 'please enter  phone',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'email',
          title: 'Email',
          label: 'Email',
          description: 'enter email',
          type: 'text',
          validationMessage: 'please enter email',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'address',
          title: 'Address',
          label: 'Address',
          description: 'enter address',
          type: 'text',
          validationMessage: 'please enter address',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'patientId',
          title: 'Patient',
          label: 'Patient',
          description: 'select patient',
          type: 'search',
          validationMessage: 'please select patient',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'relationshipTypeId',
          title: 'Relationship Type',
          label: 'Relationship Type',
          description: 'select relationship type',
          type: 'select',
          validationMessage: 'please select relationship type',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
