import { Form } from '@shared/components/form/@types/form';
import { Field } from '@shared/components/form/@types/field';
import { getNames } from 'i18n-iso-countries';

const informationFields: Field[] = [
  {
    value: '',
    name: 'firstName',
    title: 'First Name',
    label: 'First Name',
    translationPath: 'forms.patients.firstName',
    description: 'forms.patients.description',
    type: 'text',
    validationMessage: 'forms.patients.validationMessage',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'middleName',
    title: 'Middle Name',
    label: 'Middle Name',
    translationPath: 'forms.patients.middleName',
    description: 'forms.patients.descriptionEnterMiddleName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageMiddleName',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'lastName',
    title: 'Last Name',
    label: 'Last Name',
    translationPath: 'forms.patients.lastName',
    description: 'forms.patients.descriptionEnterLastName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageLastName',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'medicalRecordNo',
    title: 'ID',
    label: 'Medical record number',
    translationPath: 'forms.patients.id',
    description: 'forms.patients.descriptionId',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageId',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    title: 'Date of Birth',
    name: 'birthDate',
    label: 'Birth Date',
    translationPath: 'forms.patients.birthDate',
    description: 'forms.patients.descriptionBirthDate',
    type: 'date',
    validationMessage: 'forms.patients.validationMessageBirth',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'gender',
    title: 'Gender',
    label: 'Gender',
    translationPath: 'tables.patients.gender',
    description: 'tables.patients.selectGender',
    type: 'select',
    validationMessage: 'forms.patients.validationMessageGender',
    isRequired: false,
    options: [
      { label: 'forms.patients.gender.male', value: 'male' }, 
      { label: 'forms.patients.gender.female', value: 'female' },
      { label: 'forms.patients.gender.other', value: 'other' },
    ],
    span: 8,
  },
];



const departmentsField: Field = {
  value: '',
  name: 'departmentIds',
  title: 'Department',
  label: 'Department',
  translationPath: 'forms.patients.department',
  description: 'forms.patients.descriptionSelect',
  type: 'checkBox',
  validationMessage: 'forms.patients.validationMessageSelect',
  isRequired: false,
  options: [],
  span: 8,
};

const addressFields: Field[] = [
  {
    value: '',
    name: 'addressStreet',
    title: 'Street',
    label: 'Street',
    translationPath: 'forms.patients.street',
    description: 'forms.patients.descriptionStreetName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageStreet',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressNumber',
    title: 'Number',
    label: 'Number',
    translationPath: 'forms.patients.addressNumber',
    description: 'forms.patients.descriptionApartment',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagApartment',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressApartment',
    title: 'Apartment',
    label: 'Apartment',
    translationPath: 'forms.patients.addressApartment',
    description: 'forms.patients.descriptionApartment',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagApartment',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPlace',
    title: 'Place',
    label: 'Place',
    translationPath: 'forms.patients.addressPlace',
    description: 'forms.patients.descriptionEnterPlace',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePlace',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPostalCode',
    title: 'Postal Code',
    label: 'Postal Code',
    translationPath: 'forms.patients.addressPostalCode',
    description: 'forms.patients.descriptionEnterPostal',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePostal',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressCountryCode',
    title: 'Country',
    label: 'Country',
    translationPath: 'forms.patients.addressCountryCode',
    description: 'forms.patients.descriptionEnterCountry',
    type: 'select',
    validationMessage: 'forms.patients.validationMessageCountry',
    isRequired: false,
    span: 8,
    options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
  },
];

const contactFields: Field[] = [
  {
    value: '',
    name: 'email',
    title: 'Email Address',
    label: 'Email Address',
    translationPath: 'forms.patients.email',
    description: 'forms.patients.descriptionEnterEmail',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageEmail',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'phone',
    title: 'Phone',
    label: 'Phone',
    translationPath: 'forms.patients.phone',
    description: 'forms.patients.descriptionPhone',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePhone',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'phone2',
    title: 'Phone (alternative)',
    label: 'Phone (alternative)',
    translationPath: 'forms.patients.phone2',
    description: 'forms.patients.descriptionPhone2',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePhone2',
    isRequired: false,
    span: 8,
  },
];

// const emergencyContactFields: Field[] = [
//   {
//     value: '',
//     name: 'emergencyContacts',
//     title: 'Emergency Contact',
//     label: 'Emergency Contact',
//     translationPath: 'forms.patients.emergencyContacts',
//     description: 'Enter emergency contact',
//     type: 'array',
//     validationMessage: 'please alternative enter phone number',
//     isRequired: false,
//     span: 24,
//     rows: [],
//     children: [
//       {
//         value: '',
//         name: 'firstName',
//         title: 'First Name',
//         label: 'First Name',
//         translationPath: 'forms.patients.firstName',
//         description: 'Enter contact first name',
//         type: 'text',
//         validationMessage: 'please enter contact first name',
//         isRequired: false,
//         span: 8,
//       },
//       {
//         value: '',
//         name: 'middleName',
//         title: 'Middle Name',
//         label: 'Middle Name',
//         translationPath: 'forms.patients.middleName',
//         description: 'Enter contact middle name',
//         type: 'text',
//         validationMessage: 'please enter contact middle name',
//         isRequired: false,
//         span: 8,
//       },
//       {
//         value: '',
//         name: 'lastName',
//         title: 'Last Name',
//         label: 'Last Name',
//         translationPath: 'forms.patients.lastName',
//         description: 'Enter contact last name',
//         type: 'text',
//         validationMessage: 'please enter contact last name',
//         isRequired: false,
//         span: 8,
//       },
//       {
//         value: '',
//         name: 'email',
//         title: 'Email',
//         label: 'Email',
//         translationPath: 'forms.patients.email',
//         description: 'Enter contact email',
//         type: 'text',
//         validationMessage: 'please enter contact email',
//         isRequired: false,
//         span: 12,
//       },
//       {
//         value: '',
//         name: 'phone',
//         title: 'Phone',
//         label: 'Phone',
//         translationPath: 'forms.patients.phone',
//         description: 'Enter contact phone',
//         type: 'text',
//         validationMessage: 'please enter contact phone',
//         isRequired: false,
//         span: 12,
//       },
//     ],
//   },
// ];

const getForm = (createMode: boolean): Form => {
  return {
    submitButtonText: 'forms.patients.savePatient2',
    editButtonText: 'Edit Patient',
    submitButtonClass: 'right-align-submit',
    groups: [
      {
        title: 'Patient Information',
        translationPath: 'forms.patients.patientInformation',
        fields: createMode ? [...informationFields, departmentsField] : informationFields,
      },
      {
        title: 'Patient Address',
        translationPath: 'forms.patients.patientAddress',
        fields: addressFields,
      },
      {
        title: 'Patient Contact',
        translationPath: 'forms.patients.patientContact',
        fields: contactFields,
      },
      // {
      //   title: 'Emergency Contacts',
      //   translationPath: 'forms.patients.emergencyContacts',
      //   fields: emergencyContactFields,
      // },
    ],
  };
};

export const PatientCreateForm = getForm(true);
export const PatientUpdateForm = getForm(false);
