import { Form } from '@shared/components/form/@types/form';
import { getNames } from 'i18n-iso-countries';

export const PatientForm: Form = {
  submitButtonText: 'Save Patient',
  editButtonText: 'Edit Patient',
  submitButtonClass: 'right-align-submit',
  groups: [
    {
      title: 'Patient Information',
      fields: [
        {
          value: '',
          name: 'firstName',
          title: 'First Name',
          label: 'First Name',
          description: 'Enter first name',
          type: 'text',
          validationMessage: 'please enter first name',
          isRequired: true,
          span: 8,
        },
        {
          value: '',
          name: 'middleName',
          title: 'Middle Name',
          label: 'Middle Name',
          description: 'Enter middle name',
          type: 'text',
          validationMessage: 'please enter middle name',
          isRequired: false,
          span: 8,
        },
        {
          value: '',
          name: 'lastName',
          title: 'Last Name',
          label: 'Last Name',
          description: 'Enter last name',
          type: 'text',
          validationMessage: 'please enter last name',
          isRequired: true,
          span: 8,
        },
        {
          value: '',
          name: 'medicalRecordNo',
          title: 'ID',
          label: 'Medical record number',
          description: 'Enter medical record number',
          type: 'text',
          validationMessage: 'please enter medical record number',
          isRequired: true,
          span: 8,
        },
        {
          value: '',
          title: 'Date of Birth',
          name: 'birthDate',
          label: 'Birth Date',
          description: 'Enter date of birth',
          type: 'date',
          validationMessage: 'please enter date of birth',
          isRequired: false,
          span: 8,
        },
        {
          value: '',
          name: 'gender',
          title: 'Gender',
          label: 'Gender',
          description: 'Select Gender',
          type: 'select',
          validationMessage: 'please select gender',
          isRequired: false,
          options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
          ],
          span: 8,
        },
      ],
    },
    {
      title: 'Patient Address',
      fields: [
        {
          value: '',
          name: 'addressStreet',
          title: 'Street',
          label: 'Street',
          description: 'enter street name',
          type: 'text',
          validationMessage: 'please enter street name',
          isRequired: false,
          options: [],
          span: 8,
        },
        {
          value: '',
          name: 'addressNumber',
          title: 'Number',
          label: 'Number',
          description: 'enter number',
          type: 'text',
          validationMessage: 'please enter number',
          isRequired: false,
          options: [],
          span: 8,
        },
        {
          value: '',
          name: 'addressApartment',
          title: 'Apartment',
          label: 'Apartment',
          description: 'enter apartment number',
          type: 'text',
          validationMessage: 'please enter apartment number',
          isRequired: false,
          options: [],
          span: 8,
        },
        {
          value: '',
          name: 'addressPlace',
          title: 'Place',
          label: 'Place',
          description: 'enter place',
          type: 'text',
          validationMessage: 'please enter place',
          isRequired: false,
          options: [],
          span: 8,
        },
        {
          value: '',
          name: 'addressPostalCode',
          title: 'Postal Code',
          label: 'Postal Code',
          description: 'enter postal code',
          type: 'text',
          validationMessage: 'please enter postal code',
          isRequired: false,
          options: [],
          span: 8,
        },
        {
          value: '',
          name: 'addressCountryId',
          title: 'Country',
          label: 'Country',
          description: 'Select Country',
          type: 'select',
          validationMessage: 'please select country',
          isRequired: false,
          span: 8,
          options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
        },
      ],
    },
    {
      title: 'Patient Contact',
      fields: [
        {
          value: '',
          name: 'email',
          title: 'Email Address',
          label: 'Email Address',
          description: 'Enter email address',
          type: 'text',
          validationMessage: 'please enter email address',
          isRequired: false,
          span: 8,
        },
        {
          value: '',
          name: 'phone',
          title: 'Phone',
          label: 'Phone',
          description: 'Enter phone number',
          type: 'text',
          validationMessage: 'please enter phone number',
          isRequired: false,
          span: 8,
        },
        {
          value: '',
          name: 'phone2',
          title: 'Phone (alternative)',
          label: 'Phone (alternative)',
          description: 'Enter alternative phone number',
          type: 'text',
          validationMessage: 'please alternative enter phone number',
          isRequired: false,
          span: 8,
        },
      ],
    },
    {
      title: 'Emergency Contacts',
      fields: [
        {
          value: '',
          name: 'emergencyContacts',
          title: 'Emergency Contact',
          label: 'Emergency Contact',
          description: 'Enter emergency contact',
          type: 'array',
          validationMessage: 'please alternative enter phone number',
          isRequired: false,
          span: 24,
          rows: [],
          children: [
            {
              value: '',
              name: 'firstName',
              title: 'First Name',
              label: 'First Name',
              description: 'Enter contact first name',
              type: 'text',
              validationMessage: 'please enter contact first name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'middleName',
              title: 'Middle Name',
              label: 'Middle Name',
              description: 'Enter contact middle name',
              type: 'text',
              validationMessage: 'please enter contact middle name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'lastName',
              title: 'Last Name',
              label: 'Last Name',
              description: 'Enter contact last name',
              type: 'text',
              validationMessage: 'please enter contact last name',
              isRequired: false,
              span: 8,
            },
            {
              value: '',
              name: 'email',
              title: 'Email',
              label: 'Email',
              description: 'Enter contact email',
              type: 'text',
              validationMessage: 'please enter contact email',
              isRequired: false,
              span: 12,
            },
            {
              value: '',
              name: 'phone',
              title: 'Phone',
              label: 'Phone',
              description: 'Enter contact phone',
              type: 'text',
              validationMessage: 'please enter contact phone',
              isRequired: false,
              span: 12,
            },
          ],
        },
      ],
    },
  ],
};
