import { Form } from '../../../@shared/components/field-generator/form';

export const PatientFilterForm: Form = {
  groups: [
    {
      fields: [
        {
          title: '',
          label: 'Medical Record No',
          name: 'medicalRecordNo',
          type: 'text',
          isRequired: false,
          description: 'Hospital ID',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'First name',
          name: 'firstName',
          type: 'text',
          isRequired: false,
          description: 'First name',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Middle name',
          name: 'middleName',
          type: 'text',
          isRequired: false,
          description: 'Middle name',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Last name',
          name: 'lastName',
          type: 'text',
          isRequired: false,
          description: 'Last name',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Phone',
          name: 'phone',
          type: 'text',
          isRequired: false,
          description: 'Phone',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Email',
          name: 'email',
          type: 'text',
          isRequired: false,
          description: 'Email',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Address',
          name: 'address',
          type: 'text',
          isRequired: false,
          description: 'Address',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          title: '',
          label: 'Nationality',
          name: 'nationality',
          type: 'text',
          isRequired: false,
          description: 'Nationality',
          validationMessage: '',
          span: 24,
          value: '',
        },
        {
          value: '',
          title: '',
          name: 'active',
          label: 'Status',
          description: 'Status',
          type: 'radio',
          validationMessage: 'please enter value',
          isRequired: false,
          options: [
            { label: 'Active', value: true },
            { label: 'Archived', value: false },
          ],
          span: 24,
        },
        {
          value: '',
          title: '',
          name: 'gender',
          label: 'Gender',
          description: 'Gender',
          type: 'select',
          validationMessage: 'please enter value',
          isRequired: false,
          options: [
            { label: 'Male', value: 'male' },
            { label: 'Female', value: 'female' },
          ],
          span: 24,
        },
        {
          value: '',
          title: '',
          label: 'Date Registered',
          name: 'createdAt',
          description: 'Enter date',
          type: 'dateRange',
          validationMessage: 'please choose date range',
          isRequired: false,
          span: 24,
        },
      ],
    },
  ],
};
