import { Form } from '../../../../@shared/components/form/@types/form';
import { Setting } from '../../@types/setting';

const general: Form & { groups: { fields: { name: keyof Setting }[] }[] } = {
  submitButtonText: 'Save',
  groups: [
    {
      fields: [
        {
          title: 'Set system locale',
          name: 'systemLocale',
          label: 'Set system localed',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Set system locale',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set system time zone',
          name: 'systemTimezone',
          label: 'Set system time zone',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Set system time zone',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set date format',
          name: 'dateFormat',
          label: 'Set date format',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Set date format',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Set time format',
          name: 'timeFormat',
          label: 'Set time format',
          type: 'select',
          options: [],
          isRequired: false,
          description: 'Set time format',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Password life time (In Days)',
          name: 'passwordLifeTimeInDays',
          label: 'Set password life time',
          type: 'number',
          isRequired: false,
          description: 'Set password life time',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Password re-use cut off(In Days)',
          name: 'passwordReUseCutoffInDays',
          label: 'Set password re-use cut off',
          type: 'number',
          isRequired: false,
          description: 'Set password re-use cut off',
          validationMessage: '',
          span: 8,
          value: '',
        },
        {
          title: 'Max login attempts',
          name: 'maxLoginAttempts',
          label: 'Max login attempts',
          type: 'number',
          isRequired: false,
          description: 'Set the number of max login attempts',
          validationMessage: '',
          span: 8,
          value: undefined,
        },
      ],
    },
  ],
};

export const settingsForms = {
  general,
};
