import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgxInputSearchModule } from 'ngx-input-search';
import {
  NzAffixModule,
  NzAlertModule,
  NzAnchorModule,
  NzAutocompleteModule,
  NzAvatarModule,
  NzBackTopModule,
  NzBadgeModule,
  NzBreadCrumbModule,
  NzButtonModule,
  NzCalendarModule,
  NzCardModule,
  NzCarouselModule,
  NzCascaderModule,
  NzCheckboxModule,
  NzCollapseModule,
  NzCommentModule,
  NzNoAnimationModule,
  NzTransButtonModule,
  NzWaveModule,
  NzDatePickerModule,
  NzDescriptionsModule,
  NzDividerModule,
  NzDrawerModule,
  NzDropDownModule,
  NzEmptyModule,
  NzFormModule,
  NzGridModule,
  NzI18nModule,
  NzIconModule,
  NzInputModule,
  NzInputNumberModule,
  NzLayoutModule,
  NzListModule,
  NzMentionModule,
  NzMenuModule,
  NzMessageModule,
  NzModalModule,
  NzNotificationModule,
  NzPageHeaderModule,
  NzPaginationModule,
  NzPopconfirmModule,
  NzPopoverModule,
  NzProgressModule,
  NzRadioModule,
  NzRateModule,
  NzResultModule,
  NzSelectModule,
  NzSkeletonModule,
  NzSliderModule,
  NzSpinModule,
  NzStatisticModule,
  NzStepsModule,
  NzSwitchModule,
  NzTableModule,
  NzTabsModule,
  NzTagModule,
  NzTimePickerModule,
  NzTimelineModule,
  NzToolTipModule,
  NzTransferModule,
  NzTreeModule,
  NzTreeSelectModule,
  NzTypographyModule,
  NzUploadModule,
} from 'ng-zorro-antd';
import { FormComponent } from './form.component';
import { TextInputComponent } from './input-types/text-input/text-input.component';
import { NumberInputComponent } from './input-types/number-input/number-input.component';
import { PasswordInputComponent } from './input-types/password-input/password-input.component';
import { SearchInputComponent } from './input-types/search-input/search-input.component';
import { TextAreaInputComponent } from './input-types/text-area-input/text-area-input.component';
import { CheckBoxInputComponent } from './input-types/check-box-input/check-box-input.component';
import { RadioInputComponent } from './input-types/radio-input/radio-input.component';
import { SelectInputComponent } from './input-types/select-input/select-input.component';
import { DateInputComponent } from './input-types/date-input/date-input.component';
import { DateRangeInputComponent } from './input-types/date-range-input/date-range-input.component';

const antModules = [
  NzAffixModule,
  NzAlertModule,
  NzAnchorModule,
  NzAutocompleteModule,
  NzAvatarModule,
  NzBackTopModule,
  NzBadgeModule,
  NzBreadCrumbModule,
  NzButtonModule,
  NzCalendarModule,
  NzCardModule,
  NzCarouselModule,
  NzCascaderModule,
  NzCheckboxModule,
  NzCollapseModule,
  NzCommentModule,
  NzNoAnimationModule,
  NzTransButtonModule,
  NzWaveModule,
  NzDatePickerModule,
  NzDescriptionsModule,
  NzDividerModule,
  NzDrawerModule,
  NzDropDownModule,
  NzEmptyModule,
  NzFormModule,
  NzGridModule,
  NzI18nModule,
  NzIconModule,
  NzInputModule,
  NzInputNumberModule,
  NzLayoutModule,
  NzListModule,
  NzMentionModule,
  NzMenuModule,
  NzMessageModule,
  NzModalModule,
  NzNotificationModule,
  NzPageHeaderModule,
  NzPaginationModule,
  NzPopconfirmModule,
  NzPopoverModule,
  NzProgressModule,
  NzRadioModule,
  NzRateModule,
  NzResultModule,
  NzSelectModule,
  NzSkeletonModule,
  NzSliderModule,
  NzSpinModule,
  NzStatisticModule,
  NzStepsModule,
  NzSwitchModule,
  NzTableModule,
  NzTabsModule,
  NzTagModule,
  NzTimePickerModule,
  NzTimelineModule,
  NzToolTipModule,
  NzTransferModule,
  NzTreeModule,
  NzTreeSelectModule,
  NzTypographyModule,
  NzUploadModule,
];

@NgModule({
  imports: [...antModules, CommonModule, FormsModule, NgxInputSearchModule, ReactiveFormsModule],
  declarations: [
    FormComponent,
    TextInputComponent,
    NumberInputComponent,
    PasswordInputComponent,
    SearchInputComponent,
    TextAreaInputComponent,
    CheckBoxInputComponent,
    RadioInputComponent,
    SelectInputComponent,
    DateInputComponent,
    DateRangeInputComponent,
  ],
  exports: [FormComponent],
  providers: [],
})
export class AppFormModule {}
